Feature/merch
Reagent992/hackathon-crm-ambassadors pull request #14
Opened 2024-03-02 14:05 UTC by sic15

1) Добалвено заполнение экана 6.1 (бюджет на мерч), так же возможность выбирать период, за который нужна информация
2) реализована возможность скачивать отчет в excel файле

2024-03-02 14:21 UTC, Reagent992 commented
Для начала:
1. Выбрана неверная ветка для мерджа. (Я сам сменю на develop)
2. Не проходят линтеры, из-за того что ты добавила новые библиотеки, но не добавила их в `requirements.txt`.
3. Не сделан `merge develop`.

2024-03-02 16:16 UTC, Reagent992 requested changes

2024-03-02 16:16 UTC, Reagent992 commented on api/v1/views/merch_view.py
> +                    str(queryset[j].__dict__[f"total_{i+1}"])
Вместо `queryset[j].__dict__[f"total_{i+1}"]` лучше использовать `getattr`, т.е. получится что-то вроде `getattr(queryset[j], f"total_{i+1}")`

2024-03-02 17:06 UTC, sic15 commented on ambassadors/migrations/0001_initial.py
а что нужно сделать?

2024-03-02 17:07 UTC, sic15 commented on ambassadors/models.py
>      )
точно нужно? оно ведь нигде не используется

2024-03-02 17:09 UTC, sic15 commented on api/v1/serializers/merch_serializer.py
> +GRAND_TOTAL = 0
потому что GRAND_TOTAL это одно и то же число для всех амбассадоров. Я не хочу считать его каждый раз. Это значение я считаю один раз и все остальные разы просто его беру. Как сделать это без global я не знаю

2024-03-02 17:14 UTC, sic15 commented on api/v1/serializers/merch_serializer.py
> +        exec("total_{} = serializers.IntegerField()".format(i))
1) переделала на f строку
2) насколько я понимаю, в этом случае массив fields придется хранить где-то.

2024-03-02 17:16 UTC, Reagent992 commented on api/v1/serializers/merch_serializer.py
> +GRAND_TOTAL = 0
Через вложенный сериализатор.
Получается нам поле `grand_total` нужно только один раз, а оно добавляется в словарь каждого амбассадора.
т.е. ответный `JSON` должен быть в подобном формате:
```JSON
{
"grand_total": "123123",
"ambassadors": [
        {/* амбассадр_1*/}, 
        {/* амбассадр_2*/}, 
}

2024-03-02 17:17 UTC, Reagent992 commented on ambassadors/models.py
>      )
Нужно, где-нибудь в другой части проекта может пригодиться или для тестирования.

2024-03-02 17:17 UTC, sic15 commented on api/v1/views/merch_view.py
> +            + self.sum_per_year(date_start, date_finish),
а чем будет легче, если мы разделим на два annotate?

2024-03-02 17:22 UTC, Reagent992 commented on api/v1/views/merch_view.py
> +            + self.sum_per_year(date_start, date_finish),
Да, через разделение на два `annotate` наверно лучше не станет.

2024-03-02 17:26 UTC, Reagent992 commented on api/v1/serializers/merch_serializer.py
> +        exec("total_{} = serializers.IntegerField()".format(i))
2. Нет, это создание атрибутов объекта сериализатор.
Не могу сказать насколько это хорошая практика, но я так делал с Джанго формами, работает.😁

2024-03-02 17:38 UTC, sic15 commented on api/v1/serializers/merch_serializer.py
> +GRAND_TOTAL = 0
в этом случае у меня должен быть исходный вьюсет написан на модели MerchModel, который будет в качестве вспомогательного вызывать сериализатор для подсчета по амбассадорам, верно? тогда как сюда прикрутить вьюсет для модели амбассадор? 
я ведь верно понимаю, что вьюсет и связаный с ним сериализатор должны работать с одной и тоже моделью? а вложенные сериализаторы работают без вьюсета вовсе?

2024-03-02 17:39 UTC, Reagent992 commented on ambassadors/migrations/0001_initial.py
Восстановить эти файлы в такое же состояние как в develop.
Это можно сделать разными способами.
Например "перезаписать все коммиты в ветке" через `git reset --soft HEAD` т.к. ты во многих коммитах "сохраняла удаление миграций"

2024-03-02 17:40 UTC, sic15 commented on api/v1/views/merch_view.py
> +
это ведь метод класса, разве его можно выносить в другой файл?

2024-03-02 17:41 UTC, sic15 commented on api/v1/views/merch_view.py
> +        date_start, date_finish = get_period(self.request)
нельзя обращаться к переменным одного метода внутри другого. self.date_start, self.date_finish не работают в другом методе

2024-03-02 17:49 UTC, sic15 commented on api/v1/views/merch_view.py
> +                    str(queryset[j].__dict__[f"total_{i+1}"])
cпасибо, не доглядела

2024-03-02 19:26 UTC, Reagent992 commented on api/v1/views/merch_view.py
> +
Я не предлагал переносить функцию `download`, а только код отвечающий за создание файла вынести в отдельную функцию, которая бы вызывалась в `def download`.

2024-03-02 19:37 UTC, Reagent992 commented on api/v1/views/merch_view.py
> +        date_start, date_finish = get_period(self.request)
Ты путаешь _области видимости_ с _назначением объекту класса атрибутов_.
Я уже проверил сам, все работает.

2024-03-02 19:40 UTC, Reagent992 commented
Еще две ошибки почему-то в дискоре написал, прочитай там пожалуйста 🫠.

2024-03-03 13:24 UTC, Reagent992 requested changes

2024-03-03 13:24 UTC, Reagent992 commented on api/v1/filters.py
> +    except Exception:
`except Exception:` не стоит использовать. 
Тут должно быть "более узкое", подходящее исключение, которое поднимает функция `datetime.strptime()`
`TypeError` или `ValueError` например.

2024-03-03 13:24 UTC, Reagent992 commented on api/v1/views/merch_view.py
> +        """Вычисление суммы, потраченной на мерч амбассадору за год."""
👆

2024-03-03 13:24 UTC, Reagent992 commented on api/v1/views/merch_view.py
> +        date_start, date_finish = get_period(self.request)
👆

2024-03-03 13:24 UTC, Reagent992 commented on api/v1/views/merch_view.py
> +    @method_decorator(vary_on_cookie)
Нам тут достаточно одного `@method_decorator(cache_page(60))`.

2024-03-03 13:45 UTC, sic15 commented on ambassadors/models.py
> +        default=0,
"У нас в моделях почти везде указано null=True, "по уму" это неправильно и надо переделать на default=0, blank=True, или delault='', blank=True для текста. Иначе будут вот такие ошибки при попытке обратиться к null, как тут с  item.delivery_cost " - из дискорда цитата поэтому и переделала везде

2024-03-04 16:19 UTC, merged