Feature/content api
Reagent992/hackathon-crm-ambassadors pull request #8
Opened 2024-02-27 20:51 UTC by Lozhkin-pa

Для эндпоинта api/v1/content/ создал вьюшку и сериализаторы на чтение и запись/редактирование.
Получения контента из формы сделал экшеном api/v1/content/forms/ с отдельным сериализатором на запись.
Сделал фильтр контента по имени амбассадора и дате.
Описание для спецификации сделаю в следующем PR.

2024-02-28 10:25 UTC, Reagent992 requested changes

2024-02-28 10:25 UTC, Reagent992 commented on api/v1/views/content_view.py
> +    queryset = Content.objects.all()
Страница контент - это список амбассадоров, а не единиц контента.
т.е. эндпоинт должен отвечать списком амбассадоров с полем "content" внутри которого находится список контента. ( = Вложенный сериализатор).

Это меняет сериализаторы, поэтому я их не смотрю пока.

2024-02-28 10:25 UTC, Reagent992 commented on api/v1/serializers/content_serializer.py
> +            "platform",
"platform" - бэклог, его нету в интерфейсе сайта, давай его лучше из сериализаторов уберем, 
В ContentSerializer амбассадора я тоже зря его включил.🫠

2024-02-28 10:30 UTC, Reagent992 commented on api/v1/views/content_view.py
> +    queryset = Content.objects.all()
Но при этом `./content/<id>`  это обращение к единице контента, т.е надо в `def get_queryset(self):` выдавать разный queryset в зависимости от типа запроса `if self.action == 'list': кверисет амбассадоров, иначе кверисет контента`, Так же выбирается сериализатор в зависимости от запроса.

2024-02-28 14:16 UTC, Reagent992 commented on api/v1/views/content_view.py
> +        detail=False,
Не, я тут ошибся, `detail=False` правильно использован.🫠

2024-02-28 17:26 UTC, Reagent992 commented on api/v1/serializers/content_serializer.py
> +    content_last = LastContentSerializer(source="content", read_only=True)
Тут можно проще, без дополнительного сериализатора
```python
    content_last = ContentSerializer(
        many=False, read_only=True, source="content.first"
    )
```

2024-02-28 17:35 UTC, Lozhkin-pa commented on api/v1/filters.py
> +    def get_guide_step(self, queryset, name, value):
А по фигме (3.1) фильтруется статус новенькие/в процессе/выполнено.)

2024-02-28 17:39 UTC, Lozhkin-pa commented on api/v1/views/content_view.py
> +            self.filterset_class = ContentFilter
Иначе при retrieve ругается на фильтр, так как ретрив использует модель Контент, а не Амбассадор. А фильтр как раз Амбассадора

2024-02-28 18:52 UTC, Reagent992 commented on api/v1/filters.py
> +    def get_guide_step(self, queryset, name, value):
Понял. Ты прав.

2024-02-29 10:01 UTC, Reagent992 approved these changes
👍

2024-02-29 10:04 UTC, merged